[project]
name = "parselqcdata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "starlingnia", email = "rahalinedophy@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "gvar>=13.1.9",
    "lsqfit>=13.3.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "polars>=1.44.2",
    "psutil>=7.2.2",
    "scipy>=1.18.1",
]

[project.scripts]
parselqcdata = "parselqcdata:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
